# Generated by Django 3.2.9 on 2022-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
