# Generated by Django 3.2.9 on 2022-04-08 09:16

import bfc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerBanner', models.ImageField(upload_to=bfc.models.upload_to_banner, verbose_name='Picture')),
            ],
            options={
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='FirstTeamStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('year_joined', models.DateField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to=bfc.models.upload_to_first_team_staff, verbose_name='Picture')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'FirstTeamStaff',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.CharField(max_length=250)),
                ('awayTeam', models.CharField(max_length=250)),
                ('scoreline_home', models.IntegerField(blank=True, null=True)),
                ('scoreline_away', models.IntegerField(blank=True, null=True)),
                ('hometeamLogo', models.ImageField(upload_to=bfc.models.upload_to_matches, verbose_name='Picture')),
                ('awayteamLogo', models.ImageField(upload_to='team-logo')),
                ('tournamentLogo', models.ImageField(upload_to='tournament-logo')),
                ('fixture_date_and_time', models.DateTimeField(help_text='format: Date/Time(eg. sun')),
                ('created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Match',
                'ordering': ['-fixture_date_and_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(db_index=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('GOALKEEPER', 'GOALKEEPER'), ('DEFENDER', 'DEFENDER'), ('MIDFIELDER', 'MIDFIELDER'), ('STRIKER', 'STRIKER'), ('LOAN', 'LOAN')], default='CHOOSE', max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('place_birth', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('jerseyNumber', models.IntegerField(null=b'I00\n')),
                ('year_signed', models.DateField()),
                ('appearance', models.CharField(default='N/A', max_length=5)),
                ('goals', models.CharField(default='N/A', max_length=5)),
                ('playerProfileImage', models.ImageField(upload_to=bfc.models.upload_to_player_profile, verbose_name='Picture')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('playerBio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PlayerProfile',
                'ordering': ('firstName',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('staffBio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=bfc.models.upload_to_staff, verbose_name='Picture')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('intro', models.TextField(blank=True, help_text='Please type the begining of the sentence here not more than 200 words', max_length=200, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('postImage', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, size=[850, 510], upload_to='post/images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_post', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='CurrentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=100, size=[850, 510], upload_to='current-update/images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('intro', models.TextField(blank=True, help_text='Please type the begining of the sentence here not more than 200 words', max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'CurrentUpdate',
                'ordering': ['-dateTime'],
            },
        ),
    ]
