# Generated by Django 3.2.9 on 2022-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfc', '0002_auto_20220408_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
